export const GET_CATEGORY_LOADING = "GET_CATEGORY_LOADING";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";

export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const GET_POST_DETAIL_LOADING = "GET_POSTS_DETAIL_LOADING";
export const GET_POST_DETAIL_ERROR = "GET_POSTS_DETAIL_ERROR";
export const GET_POST_DETAIL_SUCCESS = "GET_POSTS_DETAIL_SUCCESS";

export const GET_POSTS_BY_USER_LOADING = "GET_POSTS_BY_USER_LOADING";
export const GET_POSTS_BY_USER_ERROR = "GET_POSTS_BY_USER_ERROR";
export const GET_POSTS_BY_USER_SUCCESS = "GET_POSTS_BY_USER_SUCCESS";

export const GET_POSTS_BY_CATE_LOADING = "GET_POSTS_BY_CATE_LOADING";
export const GET_POSTS_BY_CATE_ERROR = "GET_POSTS_BY_CATE_ERROR";
export const GET_POSTS_BY_CATE_SUCCESS = "GET_POSTS_BY_CATE_SUCCESS";

export const GET_USER_BY_ID_LOADING = "GET_USER_BY_ID_LOADING";
export const GET_USER_BY_ID_ERROR = "GET_USER_BY_ID_ERROR";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";

export const GET_IMAGE_LIST_LOADING = "GET_IMAGE_LIST_LOADING";
export const GET_IMAGE_LIST_ERROR = "GET_IMAGE_LIST_ERROR";
export const GET_IMAGE_LIST_SUCCESS = "GET_IMAGE_LIST_SUCCESS";

export const UPLOAD_AVATAR_LOADING = "UPLOAD_AVATAR_LOADING";
export const UPLOAD_AVATAR_ERROR = "UPLOAD_AVATAR_ERROR";
export const UPLOAD_AVATAR_SUCCESS = "UPLOAD_AVATAR_SUCCESS";

export const GET_USER_LIST_LOADING = "GET_USER_LIST_LOADING";
export const GET_USER_LIST_ERROR = "GET_USER_LIST_ERROR";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";

export const GET_ALL_POSTS_LOADING = "GET_ALL_POSTS_LOADING";
export const GET_ALL_POSTS_ERROR = "GET_ALL_POSTS_ERROR";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const CLEAR_SEARCH_TERM = "CLEAR_SEARCH_TERM";
