import { outer, inner } from "assets/styles/globalStyles";

const headerStyle = {
  siteHeader: {
    position: "relative",
    paddingTop: "12px",
    paddingBottom: "12px",
    background: "#fff no-repeat 50% ",
    backgroundSize: "cover",
    borderBottom: "1px solid #ebebeb",
  },
  outer,
  inner,
  siteNav: {
    display: "flex",
    position: "relative",
    zIndex: 4,
    justifyContent: "space-between",
    alignItems: "flex-start",
    height: "40px",
    overflowY: "hidden",
    fontSize: "1.2rem",
    minHeight: "40px",
    padding: "0",
  },
  siteNavLeft: {
    minWidth: "100px",
    overflowX: "visible",
    overflowY: "visible",
    whiteSpace: "nowrap",
  },
  siteNavLogo: {
    display: "block",
    padding: "11px 0",
    fontSize: "1.7rem",
    lineHeight: "1em",
    fontWeight: "700",
    color: "#fff",
    textDecoration: "none",
  },
  siteImgLogo: {
    display: "block",
    width: "auto",
    height: "21px",
  },
  siteNavCenter: {
    marginLeft: "6px",
    overflowX: "auto",
    overflowY: "hidden",
    letterSpacing: ".4px",
  },
  nav: {
    display: "flex",
    listStyle: "none",
    margin: "0",
    padding: "0",
  },
  navLink: {
    display: "block",
    textTransform: "uppercase",
    margin: "0",
    padding: "0",
  },
  drawerPaper: {
    border: "none",
    bottom: "0",
    transitionProperty: "top, bottom, width",
    transitionDuration: ".2s, .2s, .35s",
    transitionTimingFunction: "linear, linear, ease",
    width: 260,
    boxShadow:
      "0 10px 30px -12px rgba(0, 0, 0, 0.42), 0 4px 25px 0px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2)",
    position: "fixed",
    display: "block",
    top: "0",
    height: "100vh",
    right: "0",
    left: "auto",
    visibility: "visible",
    overflowY: "visible",
    borderTop: "none",
    textAlign: "left",
    paddingRight: "0px",
    paddingLeft: "0",
    transition: "all 0.33s cubic-bezier(0.685, 0.0473, 0.346, 1)",
  },
  appResponsive: {
    margin: "20px 10px",
  },
};
export default headerStyle;
